# jwt
spring:
  jwt:
    secret: ${JWT_SECRET}

    redirect:
      base: ${JWT_REDIRECT_BASE}
      onboarding: ${JWT_REDIRECT_ONBOARDING}

    register-token:
      expiration-time: ${JWT_REGISTER_TOKEN_EXPIRATION_TIME}
    access-token:
      expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
    refresh-token:
      expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}