
spring:
  # jwt
  jwt:
    secret: ${JWT_SECRET}

    redirect:
      base: ${JWT_REDIRECT_BASE}
      onboarding: ${JWT_REDIRECT_ONBOARDING}

    access-token:
      expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
    refresh-token:
      expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}


  #redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}