server:
  port: 8080

spring:
  application:
    name: MyAsset

  profiles:
    active: local # local / prod

  config:
    import:
      - application-security.yml
      - application-jwt.yml
      - application-db.yml
      - env.yml

  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG



