# security : OAuth2
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code

          kakao:
            client-name: Kakao
            client-id: ${OAUTH2_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH2_KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope:
              - account_email
              - profile_nickname
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code

          naver:
            client-name: Naver
            client-id: ${OAUTH2_NAVER_CLIENT_ID}
            client-secret: ${OAUTH2_NAVER_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            scope:
              - email
              - nickname
            authorization-grant-type: authorization_code

        provider:
          kakao:  # kakao-tam : https://kakao-tam.tistory.com/54
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:  # https://developers.naver.com/docs/login/devguide/devguide.md
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 3.4.2
            token-uri: https://nid.naver.com/oauth2.0/token # 3.4.4
            user-info-uri: https://openapi.naver.com/v1/nid/me  # 3.4.5
            user-name-attribute: response
